language: python
sudo: false
matrix:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py35
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: osx
      language: generic
      python: "3.6"
      before_install:
        - brew update
        - brew install python3
        - python3 -m venv venv
        - source venv/bin/activate
      env: TOXENV=py36
    # TODO: Meta for flake8

before_install:
  - pip install coveralls

install: pip install tox

script: tox -vv

notifications:
  email: false

after_success:
  - tox -e coverage-report
  - coveralls

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
